# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[chore]"
    labels:
      - "chore"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /vendor/github.com/pelletier/go-toml/v2
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /vendor/github.com/tdewolff/minify/v2
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /vendor/github.com/uptrace/bun
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /vendor/github.com/vmihailenco/msgpack/v5
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /vendor/go.opentelemetry.io/otel
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /web/source
    schedule:
      interval: daily
