---
name: Semgrep Full Scan
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 1 * * 6'
permissions:
  contents: read

jobs:
  semgrep-full:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      runs-on: ubuntu-latest
      container:
        image: returntocorp/semgrep

      steps:
        # step 1
        - name: Harden Runner
          uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
          with:
            egress-policy: audit

        - name: clone application source code
          uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

        # step 2
        - name: full scan
          run: |
            semgrep \
              --sarif --output report.sarif \
              --metrics=off \
              --config="p/default"

        # step 3
        - name: save report as pipeline artifact
          uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
          with:
            name: report.sarif
            path: report.sarif

        # step 4
        - name: publish code scanning alerts
          uses: github/codeql-action/upload-sarif@6a28655e3dcb49cb0840ea372fd6d17733edd8a4 # v2.21.8
          with:
            sarif_file: report.sarif
            category: semgrep
